name: Generate Catalog
on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  generate-eventcatalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: './yarn.lock'

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install          

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages
        
      - name: Generate Catalog
        run: |
          yarn run generate-api
          yarn run generate-catalog
      
      - name: Stage files in folder
        run: |
          git add openapi-files/
          git add domains/
          git add queries/
          git add services/
        
      - name: Commit changes
        run: |
          git commit -m "Update EventCatalog" || echo "No changes to commit"
          git push origin gh-pages #--force # Force push to overwrite the existing gh-pages branch because workflow manages the branch
          # git config --local user.email "