name: Generate Catalog
on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  generate-eventcatalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch the full history to ensure the latest state

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

          
      - name: Print package.json
        run: cat package.json

      - name: Clean Workspace
        run: |
          rm -rf node_modules
          rm -rf yarn.lock
          rm -rf package-lock.json
          rm -rf .yarn

      - name: Install Specific Yarn Version
        run: npm install -g yarn@1.22.22
          # cache-dependency-path: './package-lock.json'

      # - name: Cache node_modules
      #   uses: actions/cache@v3
      #   with:
      #     path: node_modules
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-
      
      # - name: Clear Yarn Cache
      #   run: yarn cache clean      

      - name: Install dependencies
        run: yarn install --frozen-lockfile    

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Switch to gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Print Current Directory Structure
        run: |
          pwd
          ls -la
          tree || echo "Tree command not available"

      - name: List Yarn Scripts
        run: |
            yarn run
        
      
      - name: List npm Scripts
        run: |
            npm run
        
      - name: Generate Catalog
        run: |
          yarn run generate-api
          # npm run generate-catalog
      
      - name: Stage files in folder
        run: |
          git add openapi-files/
          git add domains/
          git add queries/
          git add services/
        
      - name: Commit changes
        run: |
          git commit -m "Update EventCatalog" || echo "No changes to commit"
          git push origin gh-pages #--force # Force push to overwrite the existing gh-pages branch because workflow manages the branch
          # git config --local user.email "