name: Generate Catalog
on:
  push:
    branches:
      - main
jobs:
  generate-eventcatalog:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm run generate-catalog

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Switch to gh-pages branch
        run: |
          git checkout -B gh-pages
      
      - name: Stage files in folder
        run: |
          git add /openapi-files
        
      - name: Commit changes
        run: |
          git commit -m "Update EventCatalog" || echo "No changes to commit"
          git push origin gh-pages
          # git config --local user.email "